name: Build Windows App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 或者你的项目所需的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build # 使用已有的构建命令

      - name: Package the app
        run: npm run build-app # 使用 build-app 脚本进行打包

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aiql-desktop-artifacts
          path: artifacts/**/* # 上传 artifacts 目录下的所有文件
          retention-days: 3 # 保留 3 天